<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="./css/bootstrap.min.css">

		<!-- Optional theme -->
		<link rel="stylesheet" href="./css/bootstrap-theme.min.css">

		<link rel="stylesheet" type="text/css" href="./css/estilo.css">
		<link rel="stylesheet" type="text/css" href="./css/login.css">


		<!-- Latest compiled and minified JavaScript -->
		<script src="./js/jquery-2.0.3.min.js"></script>
		<script src="./js/bootstrap.min.js"></script>
		<script src="./js/validaCadastro.js"></script>